app5/urls.py
from django.urls import path
from . import views

app_name = 'app5'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('add_matkul', views.add_matkul, name='add_matkul'),
    path('delete/<int:delete_id>', views.delete, name='delete')
]

story5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app5.urls'))
]

app5/models.py
from django.db import models

class Matkul(models.Model):
    nama_matkul = models.CharField(max_length=30)
    dosen = models.CharField(max_length=50)
    jumlah_sks = models.IntegerField()
    deskripsi = models.CharField(max_length=100)
    semester_tahun = models.CharField(max_length=30)
    ruang_kelas = models.CharField(max_length=50)

# Create your models here.

app5/forms.py
from django import forms

class FormMatkul(forms.Form):
    nama_matkul = forms.CharField(label='Nama matkul', max_length=30)
    dosen = forms.CharField(label='Nama dosen', max_length=50)
    jumlah_sks = forms.IntegerField(label='Jumlah SKS')
    deskripsi = forms.CharField(label='Deskripsi', max_length=100)
    semester_tahun = forms.CharField(label='Semester/Tahun', max_length=30)
    ruang_kelas = forms.CharField(label='Ruang Kelas', max_length=50)

app5/views.py
from django.shortcuts import render, redirect
from .models import Matkul
from .forms import FormMatkul

# Create your views here.
def index(request):
    response = {
        'form_matkul' : FormMatkul,
        'list_matkul' : Matkul.objects.all(),
    }

    return render(request, 'index.html', response)

def add_matkul(request):
    form = FormMatkul(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        add_matkul = Matkul.objects.create(nama_matkul=request.POST['nama_matkul'], dosen=request.POST['dosen'], 
        jumlah_sks=request.POST['jumlah_sks'], deskripsi=request.POST['deskripsi'], semester_tahun=request.POST['semester_tahun'], ruang_kelas=request.POST['ruang_kelas'])
    
    return redirect('app5:index')

def delete(request, delete_id):
   Matkul.objects.filter(id=delete_id).delete()
   return redirect('app5:index')

app5/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>Story 5 Fauzan Hanandito</title>
        <style>
            body {
                font-size: 25px;
                text-align: center;
            }

            table {
                margin: auto;
            }
        </style>
    </head>
    <body>
        <h2>Silahkan isi matkul kalian :D</h2>
        </br>
        <div>
            <form action="add_matkul" method="POST">
                {% csrf_token %}
                {{ form_matkul.as_p }}
                <button type="submit" style="font-size:20px">Submit</button>
            </form>
        </div>
        <br>
        <div>
            {% for s in list_matkul %}
            <table>
                <tr>
                    <td> {{ s.nama_matkul }} </td>
                    <td> {{ s.dosen }} </td> 
                    <td> {{ s.jumlah_sks }} </td>
                    <td> {{ s.deskripsi }} </td>
                    <td> {{ s.semester_tahun }}</td>
                    <td> {{ s.ruang_kelas }}</td>
                    <td> <a href="{% url 'app5:delete' s.id %}"><button type="button" style="font-size:20px">Delete</button></a></td>
                </tr>
            </table>
            {% endfor %}
        </div>
    </body>
</html>